#!/usr/bin/env bash
set -euo pipefail

# Backup existing files (if any) before overwriting them.
for f in .editorconfig taplo.toml rustfmt.toml clippy.toml lints.toml; do
    [[ -e "$f" ]] && cp "$f" "$f.bak.$(date +%s)"
done

cat <<'EOF' >.editorconfig
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.rs]
indent_size = 4

[*.py]
indent_size = 4

[*.md]
trim_trailing_whitespace = false   # two trailing spaces = <br> in markdown

[*.{yml,yaml}]
indent_size = 2

[*.{toml,json}]
indent_size = 2

[*.sh]
indent_size = 2
end_of_line = lf

[*.{bat,cmd,ps1}]
end_of_line = crlf

[Makefile]
indent_style = tab
EOF

cat <<'EOF' >taplo.toml
include = ["**/*.toml"]
exclude = ["target/**", "node_modules/**", "**/vendor/**"]

[formatting]
reorder_arrays = false
align_entries  = false
indent_string  = "    "
column_width   = 80

[[rule]]
include = ["**/Cargo.toml"]
formatting.inline_table_expand = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "*-dependencies", "workspace.dependencies", "features"]
formatting.reorder_keys = true

[[rule]]
include = ["Cargo.toml"]
keys = ["workspace", "members"]
formatting.reorder_arrays = true
EOF

cat <<'EOF' >rustfmt.toml
# NOTE: this config relies on unstable rustfmt options.
# Run with: `cargo +nightly fmt`

# we can't rely on contributors using .editorconfig
newline_style = "Unix"
# require the shorthand instead of it being optional
use_field_init_shorthand = true
# outdated default — `?` was unstable at the time
# additionally the `try!` macro is deprecated now
use_try_shorthand = true
# Max to use the 100 char width for everything or Default. See https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#use_small_heuristics
use_small_heuristics = "Max"

style_edition = "2024"
unstable_features = true

# better grepping
imports_granularity = "Item"
group_imports = "StdExternalCrate"

normalize_comments = true
reorder_impl_items = true
reorder_modules = true
wrap_comments = false

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
EOF

cat <<'EOF' >clippy.toml
# :schema

msrv = "1.95"

allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests  = true

# Treat the crate as internal so `clippy::pedantic` also flags would-be
# "breaking" public-API changes (we don't ship a public API anyway).
avoid-breaking-exported-api = false

type-complexity-threshold = 2000 # for our needs long types are fine

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_macros
disallowed-macros = [
    # "std::unimplemented", # generated by ArrowDeserialize derive-macro :(
]

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods
disallowed-methods = [
    { path = "std::env::temp_dir",            reason = "use the `tempfile` crate" },
    { path = "std::thread::spawn",            reason = "use `std::thread::Builder` and name the thread" },
    { path = "sha1::Digest::new",             reason = "SHA1 is cryptographically broken" },
    { path = "std::process::exit",            reason = "skips destructors; return from `main` instead" },
    { path = "tokio::sync::Mutex::blocking_lock", reason = "deadlocks the runtime" },
    { path = "std::time::SystemTime::now",    reason = "use a clock abstraction for testability" },
    # Uncomment if the project is compiled with `panic = "abort"`:
    # { path = "std::panic::catch_unwind", reason = "we compile with panic = abort" },
]

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_names
disallowed-names = []

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types
disallowed-types = [
    "std::sync::RwLock",
    "std::sync::Condvar",
    # "std::sync::Once",  # enabled for now as the `log_once` macro uses it internally
]

# Allow-list of words for markdown in docstrings https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
doc-valid-idents = []
EOF

cat <<'EOF' >lints.toml
# This file is a TEMPLATE for `[workspace.lints]` — it is NOT picked up by Cargo
# automatically. `clippy.toml` only configures behavior of specific lints, it
# does NOT enable any of them. To actually enable the lint set below, copy the
# `[rust]` and `[clippy]` tables into your workspace-root `Cargo.toml` under
# `[workspace.lints.rust]` and `[workspace.lints.clippy]` respectively, e.g.:
#
#   # workspace root Cargo.toml
#   [workspace.lints.rust]
#   unsafe_code = "deny"
#   ...
#
#   [workspace.lints.clippy]
#   pedantic = { level = "warn", priority = -1 }
#   ...
#
# Then in EVERY member crate `Cargo.toml` opt in with:
#
#   [lints]
#   workspace = true

[rust]
unsafe_code                   = "deny"
unreachable_pub               = "warn"
missing_debug_implementations = "warn"
rust_2018_idioms              = { level = "warn", priority = -1 }

[clippy]
pedantic = { level = "warn", priority = -1 }
nursery  = { level = "warn", priority = -1 }
cargo    = { level = "warn", priority = -1 }
# Selectively silence the noisy ones:
module_name_repetitions = "allow"
must_use_candidate      = "allow"
missing_errors_doc      = "allow"
EOF
