include = ["**/*.toml"]
exclude = ["target/**", "node_modules/**", "**/vendor/**"]

[formatting]
reorder_arrays = false
align_entries = false
indent_string = "    "
column_width = 80

[[rule]]
include = ["**/Cargo.toml"]
formatting.inline_table_expand = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "*-dependencies", "workspace.dependencies", "features"]
formatting.reorder_keys = true

[[rule]]
include = ["Cargo.toml"]
keys = ["workspace", "members"]
formatting.reorder_arrays = true
